name: Bug Report
description: Report a reproducible bug in frontend
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: 1) ... 2) ... 3) ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      placeholder: Browser/OS/branch/commit
