name: Feature Request
description: Propose a frontend feature or UX improvement
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      placeholder: What user problem are we solving?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      placeholder: Suggested UI/flow/behavior
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope / Out of Scope
      placeholder: Keep implementation boundaries clear
